[package]
name = "starbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serenity = { version = "0.11.5", features = ["cache"] }
sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-rustls", "time", "offline"] }
time = "0.3.16"
tokio = "1.21.2"
url = "2.3.1"
